name: asman_work
description: asman_work.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.3.1"

dependencies:
  asman_flutter_uikit:
    git:
      url: https://git.asmantiz.com/Koch/asman_flutter_uikit.git
      ref: dev_oguljemal
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.1
  geolocator: ^9.0.2
  get_storage: ^2.0.3
  go_router: ^6.0.9
  intl: ^0.17.0
  latlong2: ^0.8.1
  persistent_bottom_nav_bar: ^5.0.2
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  

  
dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/languages/

  # fonts:
  #   - family: JobIcons
  #     fonts: 
  #       - asset: assets/icons/fonts/JobIcons.ttf
  


  