name: asman_work
description: asman_work.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.3.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  asman_flutter_uikit:
    git:
      url: https://git.asmantiz.com/Koch/asman_flutter_uikit.git
      ref: dev_oguljemal
  bloc: ^8.1.0
  connectivity_plus:
  dio:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_storage: ^2.0.3
  go_router: ^5.1.0
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  persistent_bottom_nav_bar: any

  
dev_dependencies:
  bloc_test: ^9.1.0
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  generate: true

  